### ISSUE TITLE
Config Source EchoConfigSource does not return any properties

### ISSUE THREAD

**Issue by Emily-Jiang** [javaee-samples/microprofile1.2-samples#3]
@arjantijms https://api.travis-ci.org/v3/job/342573505/log.txt

shows some failures on Open Liberty. This root cause is that EchoConfigSource returns an empty map. According to the MP Config spec, the getProperties() should return a map of properties.

**Comment by arjantijms** [comment]
>This root cause is that EchoConfigSource returns an empty map. According to the MP Config spec, the getProperties() should return a map of properties.

I see, and OpenLiberty seems to grab all the names from that map. This makes it impossible to support 'dynamic' maps. I'll try to change the test, thanks Emily!

**Comment by arjantijms** [comment]
I fixed this in https://github.com/javaee-samples/microprofile1.2-samples/commit/8b0776beb13a9c612b70690f77cf71aa21f68495

Perhaps for the MP Config spec if would be an idea to be able to disable this 'protection' of declared keyword names, so sources can be dynamic. I'll talk that over with the MP people internally at Payara first.

**Comment by Emily-Jiang** [comment]
Please open an issue on MP config after your internal discussion. Let's discuss more there.

**Comment by arjantijms** [comment]
@Emily-Jiang Okay, I started a discussion about the problems here: https://groups.google.com/forum/#!topic/microprofile/d0s3uAeVec8

Would appreciate your feedback there :)
